[general]
import = [
    "themes/moonfly.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "terminus"
style = "Regular"

[font.bold]
family = "terminus"
style = "Bold"

